---
driver:
  provider: hyperv
  name: vagrant
  vm_hostname: false # do not bother trying to change the hostname (sometimes fails)
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero

platforms:
  - name: ws2012-chef11.16.4
    driver_config:
      box: ws2012
    provisioner:
      require_chef_omnibus: 11.16.4


suites:
  - name: default
    run_list:
      - recipe[iis::default]

